language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1

sudo: false

addons:
  mariadb: '10.2'

services:
  - mysql

before_install:
  - travis_retry composer self-update
  - cp laranix/.env.travis laranix/.env
  - mysql -e 'CREATE DATABASE travis_test; set global max_connections = 1001;'

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
  - php artisan key:generate

before_script:
  - phpenv config-rm xdebug.ini
  - cd $TRAVIS_BUILD_DIR/laranix

script: vendor/bin/phpunit
