language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1

sudo: false

before_install:
  - travis_retry composer self-update
  - cp .env.travis .env

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

before_script:
  - phpenv config-rm xdebug.ini
  - mysql -e 'create database homestead;'

script:
  - vendor/bin/phpunit
